#!/usr/bin/env python3
"""
Wikipedia Historical Events Scraper
=====================================
Scrapes Wikipedia timeline pages + article summaries and outputs a CSV
ready to import into the Timeline Game admin panel.

Usage:
    pip install requests beautifulsoup4 lxml
    python scrape_wikipedia.py
    python scrape_wikipedia.py --output my_cards.csv --delay 0.5
    python scrape_wikipedia.py --limit 200   # cap total events

Output columns:
    event, year, month, day, category, description, difficulty,
    region, tags, source, wikipediaSlug, imageCaption

Notes:
  - Tags are semicolon-separated (commas are the CSV delimiter).
  - Year is negative for BC events (e.g. -44 for 44 BC).
  - IDs are auto-generated by the game server from event + year.
  - The script sleeps --delay seconds between Wikipedia API calls
    to avoid rate-limiting. Default: 0.4 s.
"""

import re
import csv
import sys
import time
import json
import argparse
import unicodedata
import shutil
from datetime import datetime
from pathlib import Path
from urllib.parse import unquote, urljoin

import requests
from bs4 import BeautifulSoup

# ── Config ─────────────────────────────────────────────────────────────────────

HEADERS = {
    "User-Agent": "TimelineGameScraper/1.0 (educational project; github.com/timeline-game)"
}
WIKI_API   = "https://en.wikipedia.org/api/rest_v1/page/summary/{slug}"
WIKI_BASE  = "https://en.wikipedia.org"

# Timeline pages to scrape (add / remove as desired)
TIMELINE_SOURCES = [
    # Ancient
    "https://en.wikipedia.org/wiki/Timeline_of_ancient_history",
    # Medieval
    "https://en.wikipedia.org/wiki/Timeline_of_the_Middle_Ages",
    # Early Modern
    "https://en.wikipedia.org/wiki/Timeline_of_the_early_modern_period",
    # 18th century
    "https://en.wikipedia.org/wiki/Timeline_of_the_18th_century",
    # 19th century
    "https://en.wikipedia.org/wiki/Timeline_of_the_19th_century",
    # 20th century
    "https://en.wikipedia.org/wiki/Timeline_of_the_20th_century",
    # 21st century
    "https://en.wikipedia.org/wiki/Timeline_of_the_21st_century",
    # Thematic timelines
    "https://en.wikipedia.org/wiki/Timeline_of_scientific_discoveries",
    "https://en.wikipedia.org/wiki/Timeline_of_historic_inventions",
    "https://en.wikipedia.org/wiki/Timeline_of_wars",
    "https://en.wikipedia.org/wiki/List_of_wars_and_anthropogenic_disasters_by_death_toll",
    "https://en.wikipedia.org/wiki/Timeline_of_medicine_and_medical_technology",
    "https://en.wikipedia.org/wiki/Timeline_of_computing",
    "https://en.wikipedia.org/wiki/Timeline_of_astronomy",
    "https://en.wikipedia.org/wiki/Timeline_of_the_Space_Race",
    "https://en.wikipedia.org/wiki/Timeline_of_exploration",
    "https://en.wikipedia.org/wiki/Timeline_of_natural_disasters",
    "https://en.wikipedia.org/wiki/Timeline_of_religious_history",
    "https://en.wikipedia.org/wiki/Timeline_of_art_history",
    "https://en.wikipedia.org/wiki/Timeline_of_music",
    "https://en.wikipedia.org/wiki/Timeline_of_the_evolutionary_history_of_life",
]

# ── Categorisation ─────────────────────────────────────────────────────────────

SCIENCE_KW = {
    "invent", "discover", "scientist", "telescope", "vaccine", "vaccination",
    "computer", "physics", "chemistry", "biology", "astronomy", "mathematics",
    "theorem", "theory", "experiment", "laboratory", "microscope", "electricity",
    "nuclear", "atom", "electron", "quantum", "genome", "dna", "rna", "cell",
    "element", "periodic", "equation", "calculus", "gravity", "relativity",
    "antibiotic", "penicillin", "surgery", "medicine", "virus", "bacteria",
    "rocket", "satellite", "spacecraft", "telescope", "radio", "telegraph",
    "telephone", "television", "internet", "semiconductor", "transistor",
    "artificial intelligence", "machine learning", "robotics", "printing press",
    "steam engine", "locomotive", "automobile", "aeroplane", "airplane",
    "aircraft", "flight", "aviation",
}

WAR_KW = {
    "war", "battle", "siege", "invasion", "revolution", "revolt", "rebellion",
    "assassination", "empire", "kingdom", "treaty", "peace", "armistice",
    "independence", "colonise", "colonize", "occupation", "liberation",
    "coup", "dictatorship", "monarchy", "republic", "democracy", "election",
    "constitution", "parliament", "senate", "congress", "president", "prime minister",
    "king", "queen", "emperor", "dynasty", "crusade", "jihad", "genocide",
    "holocaust", "concentration camp", "nuclear bomb", "cold war",
    "annexation", "partition", "civil war", "military", "army", "navy",
    "treason", "executed", "guillotine",
}

ARTS_KW = {
    "art", "paint", "sculpture", "architect", "architecture", "music",
    "composer", "symphony", "opera", "theatre", "theater", "film", "cinema",
    "novel", "literature", "poem", "poetry", "philosopher", "philosophy",
    "religion", "church", "cathedral", "mosque", "temple", "bible",
    "quran", "buddhism", "hinduism", "christianity", "islam", "judaism",
    "monastery", "papacy", "pope", "protestant", "reformation", "renaissance",
    "baroque", "impressionism", "romanticism", "modernism", "surrealism",
    "ballet", "dance", "photograph", "printing", "newspaper", "university",
    "school", "library",
}

EXPLORATION_KW = {
    "exploration", "explorer", "voyage", "expedition", "discover", "circumnavigate",
    "navigate", "navigation", "continent", "island", "route", "trade route",
    "silk road", "spice", "colony", "settlement", "earthquake", "volcano",
    "eruption", "tsunami", "flood", "hurricane", "famine", "plague", "epidemic",
    "pandemic", "disaster", "shipwreck", "avalanche", "drought", "wildfire",
    "migrate", "migration", "colonisation", "new world", "cape",
}


def categorise(text: str) -> str:
    t = text.lower()
    scores = {
        "science-technology":    sum(1 for k in SCIENCE_KW     if k in t),
        "war-politics":          sum(1 for k in WAR_KW         if k in t),
        "art-culture-religion":  sum(1 for k in ARTS_KW        if k in t),
        "exploration-disasters": sum(1 for k in EXPLORATION_KW if k in t),
    }
    return max(scores, key=scores.get) if max(scores.values()) > 0 else "war-politics"


# ── Region detection ───────────────────────────────────────────────────────────

REGION_MAP = {
    "europe":       ["europe","britain","england","france","germany","italy","spain",
                     "portugal","greece","roman","ottoman","byzantine","austrian",
                     "russian","dutch","netherlands","swedish","polish","hungarian",
                     "swiss","scottish","irish","viking","norse","scandinavia"],
    "asia":         ["china","japan","india","korea","persia","mongol","ottoman",
                     "mesopotamia","babylon","assyrian","sumerian","silk road",
                     "cambodia","vietnam","thailand","philippines","indonesia"],
    "middle east":  ["egypt","mesopotamia","babylon","persia","israel","palestine",
                     "ottoman","arab","islamic","crusade","jerusalem","saudi","iraq",
                     "iran","syria","lebanon","jordan","turkey"],
    "africa":       ["africa","egypt","ethiopia","sahara","mali","ghana","zulu",
                     "carthage","nubia","congo","kenya","nigeria"],
    "americas":     ["america","united states","usa","canada","mexico","brazil",
                     "argentina","colombia","aztec","maya","inca","caribbean",
                     "cuba","haiti","peru","chile","new world"],
    "global":       ["world","global","international","universal","earth"],
    "oceania":      ["australia","new zealand","pacific","polynesia","maori"],
}


def detect_region(text: str) -> str:
    t = text.lower()
    for region, kws in REGION_MAP.items():
        if any(k in t for k in kws):
            return region.title()
    return "Global"


# ── Year parsing ───────────────────────────────────────────────────────────────

_YEAR_RE = re.compile(
    r"""
    (?:^|\s|[(\[])
    (c\.?\s*)?                      # circa
    (\d{1,4})                       # year digits
    \s*
    (BC|BCE|AD|CE)?                 # era
    (?:\s|$|[)\]])
    """,
    re.VERBOSE | re.IGNORECASE,
)


def parse_year(text: str):
    """Return (year: int, month: int|None, day: int|None) or None."""
    # Try ISO date first: YYYY-MM-DD
    m = re.search(r"\b(\d{4})-(\d{2})-(\d{2})\b", text)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3))

    # Try "Month DD, YYYY"
    months = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,
              "july":7,"august":8,"september":9,"october":10,"november":11,"december":12}
    m = re.search(r"(\w+)\s+(\d{1,2}),?\s+(\d{4})", text, re.IGNORECASE)
    if m and m.group(1).lower() in months:
        return int(m.group(3)), months[m.group(1).lower()], int(m.group(2))

    # Generic year + era
    m = _YEAR_RE.search(text)
    if m:
        y = int(m.group(2))
        era = (m.group(3) or "AD").upper()
        if "BC" in era or "BCE" in era:
            y = -y
        return y, None, None

    return None


# ── Difficulty heuristic ───────────────────────────────────────────────────────

# Very well-known events → difficulty 1
EASY_KW = {
    "world war", "moon landing", "apollo", "revolution", "independence",
    "discovery of america", "columbus", "black death", "plague", "renaissance",
    "industrial revolution", "civil war", "abolition", "magna carta",
    "gutenberg", "fall of rome", "fall of constantinople", "pyramid",
    "einstein", "darwin", "newton", "shakespeare", "napoleon",
    "french revolution", "american revolution", "russian revolution",
    "hiroshima", "berlin wall", "cold war", "internet", "dna",
    "penicillin", "vaccination", "wright brothers", "titanic",
    "chernobyl", "9/11", "september 11",
}

HARD_KW = {
    "treaty of", "battle of", "siege of", "council of", "diet of",
    "edict of", "congress of", "synod", "encyclical", "concordat",
    "proclamation", "ordinance", "statute", "charter",
}


def difficulty(event: str, desc: str) -> int:
    combined = (event + " " + desc).lower()
    if any(k in combined for k in EASY_KW):
        return 1
    if any(k in combined for k in HARD_KW):
        return 3
    return 2


# ── Tag extraction ─────────────────────────────────────────────────────────────

TAG_CANDIDATES = [
    "war", "science", "technology", "art", "music", "religion", "exploration",
    "politics", "medicine", "astronomy", "physics", "chemistry", "biology",
    "architecture", "literature", "philosophy", "revolution", "empire",
    "discovery", "invention", "space", "aviation", "computing", "internet",
    "disaster", "earthquake", "volcano", "plague", "pandemic", "famine",
    "treaty", "independence", "colonisation", "trade", "economy",
    "africa", "asia", "europe", "americas", "middle east", "oceania",
    "ancient", "medieval", "modern", "renaissance", "enlightenment",
    "democracy", "monarchy", "republic", "socialism", "communism",
    "nuclear", "atomic", "genetics", "evolution", "climate",
]


def extract_tags(text: str) -> list:
    t = text.lower()
    return [tag for tag in TAG_CANDIDATES if tag in t][:6]


# ── Slug normalisation ─────────────────────────────────────────────────────────

def wiki_slug(url_or_title: str) -> str:
    """Extract the Wikipedia article slug from a URL or raw title."""
    if url_or_title.startswith("http"):
        slug = url_or_title.split("/wiki/")[-1]
    else:
        slug = url_or_title
    slug = unquote(slug).replace(" ", "_")
    # Remove section anchors
    slug = slug.split("#")[0]
    return slug


# ── Wikipedia scraping ─────────────────────────────────────────────────────────

SESSION = requests.Session()
SESSION.headers.update(HEADERS)


def fetch_page(url: str) -> BeautifulSoup | None:
    try:
        r = SESSION.get(url, timeout=15)
        r.raise_for_status()
        return BeautifulSoup(r.text, "lxml")
    except Exception as e:
        print(f"  [warn] Could not fetch {url}: {e}", file=sys.stderr)
        return None


def fetch_summary(slug: str) -> dict | None:
    url = WIKI_API.format(slug=requests.utils.quote(slug, safe=""))
    try:
        r = SESSION.get(url, timeout=12)
        if r.status_code == 200:
            return r.json()
    except Exception:
        pass
    return None


def extract_events_from_timeline(soup: BeautifulSoup, page_url: str) -> list[dict]:
    """
    Parse a Wikipedia timeline page and return a list of raw event dicts with:
    text, year, month, day, wiki_url (if a wikilink was found).
    """
    events = []
    seen_links = set()

    # Most timeline pages use <li> items containing a year and an event
    for li in soup.select("li"):
        raw = li.get_text(" ", strip=True)
        if len(raw) < 20 or len(raw) > 600:
            continue

        parsed = parse_year(raw)
        if not parsed:
            continue
        year, month, day = parsed
        if abs(year) > 2025:
            continue

        # Find the first internal wiki link in this <li>
        link = None
        for a in li.find_all("a", href=True):
            href = a["href"]
            if href.startswith("/wiki/") and ":" not in href and "#" not in href:
                link = WIKI_BASE + href
                break

        if link and link in seen_links:
            continue
        if link:
            seen_links.add(link)

        events.append({
            "raw_text": raw,
            "year": year,
            "month": month,
            "day": day,
            "wiki_url": link,
        })

    return events


def build_card(raw: dict, delay: float) -> dict | None:
    """
    Given a raw event dict, fetch the Wikipedia summary and build a card dict.
    Returns None if we can't get enough data.
    """
    wiki_url = raw.get("wiki_url")
    slug = wiki_slug(wiki_url) if wiki_url else None

    summary = None
    if slug:
        time.sleep(delay)
        summary = fetch_summary(slug)

    # Use the summary title as event name if we have it
    event_name = (summary or {}).get("title", "")
    if not event_name:
        # Fall back: try to clean the raw text
        text = raw["raw_text"]
        # Remove leading year references
        text = re.sub(r"^\s*\d{1,4}\s*(BC|BCE|AD|CE)?\s*[:\-–—]?\s*", "", text, flags=re.IGNORECASE)
        event_name = text[:80].strip(" .,;")
        if len(event_name) < 5:
            return None

    description = (summary or {}).get("extract", "")
    if description:
        # Truncate to ~400 chars but end at a sentence boundary
        if len(description) > 400:
            short = description[:400]
            last_dot = short.rfind(".")
            description = short[: last_dot + 1] if last_dot > 100 else short
    else:
        description = raw["raw_text"][:280].strip()

    if not description:
        return None

    combined = event_name + " " + description
    category = categorise(combined)
    region   = detect_region(combined)
    tags     = extract_tags(combined)
    diff     = difficulty(event_name, description)
    image_caption = (summary or {}).get("description", "")

    card = {
        "event":         event_name,
        "year":          raw["year"],
        "category":      category,
        "description":   description,
        "difficulty":    diff,
        "region":        region,
        "tags":          ";".join(tags),
        "source":        wiki_url or "",
        "wikipediaSlug": slug or "",
        "imageCaption":  image_caption,
    }
    if raw.get("month"):
        card["month"] = raw["month"]
    if raw.get("day"):
        card["day"] = raw["day"]

    return card


# ── Terminal UI helpers ────────────────────────────────────────────────────────

# ANSI colours (disabled automatically on Windows if not supported)
_USE_COLOR = sys.stderr.isatty()

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text

def cyan(t):   return _c("96", t)
def green(t):  return _c("92", t)
def yellow(t): return _c("93", t)
def red(t):    return _c("91", t)
def dim(t):    return _c("2",  t)
def bold(t):   return _c("1",  t)

CAT_COLOUR = {
    "science-technology":    cyan,
    "war-politics":          red,
    "art-culture-religion":  yellow,
    "exploration-disasters": green,
}

def draw_progress(done: int, total: int, skipped: int, errors: int, width: int = 40) -> None:
    """Redraw the progress bar line in place."""
    pct   = done / max(total, 1)
    filled = int(width * pct)
    bar   = "█" * filled + "░" * (width - filled)
    colour = green if pct >= 1 else cyan
    line  = (
        f"  {colour(bar)}  "
        f"{bold(str(done))}/{bold(str(total))} cards"
        f"  {dim(f'skip:{skipped}  err:{errors}')}"
        f"  {dim(f'{pct*100:.0f}%')}"
    )
    # Clear line and rewrite
    print(f"\r\033[K{line}", end="", file=sys.stderr, flush=True)


def log_card(card: dict, status: str = "ok") -> None:
    """Print a single log line for a card (below the progress bar)."""
    ts      = dim(datetime.now().strftime("%H:%M:%S"))
    cat_fn  = CAT_COLOUR.get(card.get("category", ""), dim)
    cat     = cat_fn(f"[{card.get('category','?')[:4].upper()}]")
    year    = bold(str(card.get("year", "?")))
    event   = card.get("event", "?")[:60]
    icon    = green("✓") if status == "ok" else yellow("~") if status == "skip" else red("✗")
    # Move up past progress bar, print log, reprint bar
    print(f"\r\033[K  {ts}  {icon}  {cat}  {year}  {event}", file=sys.stderr)


def log(msg: str, colour_fn=None) -> None:
    fn  = colour_fn or (lambda x: x)
    print(f"\r\033[K  {fn(msg)}", file=sys.stderr)


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output",  default="timeline_cards.csv",
                        help="Output CSV file path (default: timeline_cards.csv)")
    parser.add_argument("--delay",   type=float, default=0.4,
                        help="Seconds to sleep between Wikipedia API calls (default: 0.4)")
    parser.add_argument("--limit",   type=int,   default=0,
                        help="Max total cards to generate (0 = no limit)")
    parser.add_argument("--sources", nargs="*",
                        help="Override timeline URLs to scrape (space-separated)")
    parser.add_argument("--quiet",   action="store_true",
                        help="Only show progress bar, suppress per-card logs")
    args = parser.parse_args()

    sources  = args.sources or TIMELINE_SOURCES
    out_path = Path(args.output)
    limit    = args.limit or 0

    CSV_COLS = [
        "event", "year", "month", "day", "category", "description",
        "difficulty", "region", "tags", "source", "wikipediaSlug", "imageCaption",
    ]

    # Header
    term_w = shutil.get_terminal_size((80, 20)).columns
    print(file=sys.stderr)
    print(f"  {bold('TIMELINE GAME — Wikipedia Scraper')}", file=sys.stderr)
    print(f"  {dim('─' * min(term_w - 4, 60))}", file=sys.stderr)
    print(f"  Target : {bold(str(limit) + ' cards' if limit else 'unlimited')}", file=sys.stderr)
    print(f"  Delay  : {bold(str(args.delay) + 's')} per API call", file=sys.stderr)
    print(f"  Output : {bold(str(out_path))}", file=sys.stderr)
    print(f"  Sources: {bold(str(len(sources)))} timeline pages", file=sys.stderr)
    print(file=sys.stderr)

    total_written = 0
    total_skipped = 0
    total_errors  = 0
    seen_slugs    = set()
    start_time    = time.time()

    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLS, extrasaction="ignore")
        writer.writeheader()

        for src_idx, page_url in enumerate(sources):
            if limit and total_written >= limit:
                break

            page_name = page_url.split("/wiki/")[-1].replace("_", " ")
            log(f"[{src_idx+1}/{len(sources)}] Fetching: {page_name}", cyan)

            soup = fetch_page(page_url)
            if not soup:
                log(f"  ✗ Could not fetch {page_url}", red)
                continue

            raw_events = extract_events_from_timeline(soup, page_url)
            log(f"  → {len(raw_events)} candidate events found on this page", dim)

            for raw in raw_events:
                if limit and total_written >= limit:
                    break

                slug = wiki_slug(raw["wiki_url"]) if raw.get("wiki_url") else ""
                if slug and slug in seen_slugs:
                    total_skipped += 1
                    draw_progress(total_written, limit or total_written + 1,
                                  total_skipped, total_errors)
                    continue

                card = build_card(raw, args.delay)

                if not card:
                    total_errors += 1
                    draw_progress(total_written, limit or total_written + 1,
                                  total_skipped, total_errors)
                    continue

                if card["wikipediaSlug"] and card["wikipediaSlug"] in seen_slugs:
                    total_skipped += 1
                    draw_progress(total_written, limit or total_written + 1,
                                  total_skipped, total_errors)
                    continue

                if card["wikipediaSlug"]:
                    seen_slugs.add(card["wikipediaSlug"])

                writer.writerow(card)
                f.flush()
                total_written += 1

                if not args.quiet:
                    log_card(card, "ok")

                draw_progress(total_written, limit or total_written,
                              total_skipped, total_errors)

    # Footer
    elapsed = time.time() - start_time
    print(file=sys.stderr)
    print(file=sys.stderr)
    print(f"  {dim('─' * min(term_w - 4, 60))}", file=sys.stderr)
    print(f"  {green('Done!')}  {bold(str(total_written))} cards written to {bold(str(out_path))}", file=sys.stderr)
    print(f"  Skipped {total_skipped} duplicates  •  {total_errors} errors  •  {elapsed:.0f}s elapsed", file=sys.stderr)
    print(file=sys.stderr)


if __name__ == "__main__":
    main()
